Update scout.yml

diff --git a/.github/workflows/scout.yml b/.github/workflows/scout.yml
--- a/.github/workflows/scout.yml
+++ b/.github/workflows/scout.yml
@@ -7,7 +7,7 @@ on:
       - 'main'
   pull_request:
     branches: [ "**" ]
-    
+
 env:
   REGISTRY: docker.io
   IMAGE_NAME: erickdaniel0/dockerscout
@@ -25,7 +25,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ env.SHA }}
-          
+
       - name: Setup Docker buildx
         uses: docker/setup-buildx-action@v2.5.0
 
@@ -44,7 +44,7 @@ jobs:
           labels: |
             org.opencontainers.image.revision=${{ env.SHA }}
           tags: |
-            type=edge,branch=${{ github.ref_name }}
+            type=edge,branch=$repo.default_branch
             type=semver,pattern=v{{version}}
             type=sha,prefix=,suffix=,format=short
 
@@ -58,20 +58,15 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-          
-      # Usar contenedor con Docker Scout instalado
-      - name: Run Docker Scout analysis inside a container
+
+      # Usar el nombre de la imagen y la etiqueta generada para el análisis
+      - name: Docker Scout - Save report to text file
         id: docker-scout
         if: ${{ github.event_name == 'pull_request' }}
         run: |
-          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}"
+          IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
           echo "Running Docker Scout analysis on image: $IMAGE_TAG"
-          
-          # Ejecutar Docker Scout dentro de un contenedor que tenga Docker Scout preinstalado
-          docker run --rm \
-            -v /var/run/docker.sock:/var/run/docker.sock \
-            -v $(pwd):/workspace \
-            docker/scout-cli cves $IMAGE_TAG > docker_scout_report.txt || echo "Docker Scout failed to generate report"
+          docker scout cves "$IMAGE_TAG" > docker_scout_report.txt || echo "Docker Scout failed to generate report"
 
       - name: Upload Docker Scout Report as Artifact
         uses: actions/upload-artifact@v3
